### ISSUE TITLE
Problem in listing flavors / images from different locations / projects / domains (Giessen)

### ISSUE THREAD

**Issue by tdilger** [BiBiServ/bibigrid#235]
It seems to be a problem regarding openstack4j versions. 3.0.0 seems to work out, 3.2 does not

**Comment by jkrue** [comment]
This is not a problem with the de.NBI cloud site Giessen. The problem occurs, when the target project is not located in the `default` domain.

**Comment by jkrue** [comment]
The problem is triggered by two independent things : 

1. de.NBI Cloud site Giessen offers **two** endpoints for Openstack placement. One is named 'placement' (as suggested in the Openstack configuration manual), and the other one is named 'nova'. Unfortunately the Openstack compute service is also named 'nova', so nova as name for a server is not unique anymore. I asked the administrator to correct this obviously misconfiguration. 
2. Openstack4Js DefaultEndpointURLResolver selects a service endpoint for given service type when the type **or** the name matches. In the scenario described above it could be then happend (depending on the catalog order) the placement endpoint is chosen for service type COMPUTE.

**Comment by jkrue** [comment]
openstack4j is patched, a PR is made
