### ISSUE TITLE
Test Slurm-web as user-friendly web ui for slurm. 

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#239]
We should give [Slurm-Web](https://edf-hpc.github.io/slurm-web) a try to provide a web based UI for Slurm.

This issue will be examined by two students as part of a lecture at Bielefeld university.

**Comment by UBDeniz** [comment]
# Description
The purpose of this project is to test a web application called Slurm-web (v19.05) on Ubuntu 20.04. Slurm-web implies to provides a web frontend with a running Slurm workload manager. It is based 3 components:
1. A backend REST API: The REST API provides runtime data of a system running Slurm. All data are provided in JSON format. 
2. Dashboard web GUI: The dashboard demonstrates all supercomputer runtime data. The user can navigate between the view jobs, racks, jobsMap, 3D view, Partitions, QOS, Reservations, Gantt and Topology. 
3. server for dashboard’s configuration files.   
The project is to test if the application can be used for future projects and what changes may have to be made. 

#     2. Procedure
At the first  attampt, slurm was installed with the specified instructions from the website (https://edf-hpc.github.io/slurm-web/) into a docker container. Therefore we had to costemize the confguration flies to make sure that all moduels exists and refer to the right path. To run it on a virutal instance we had to create a SSH Tunneling (Port Forwarding) with:

```sh
ssh -L [LOCAL_IP:]LOCAL_PORT:DESTINATION:DESTINATION_PORT [USER@]SSH_SERVER
```

To review if every was running correctly, we checkt that the conatiner is running with docker ps, and accessed the Slurm-web interface by pointing the browser to http://localhost:1119/slurm. 
We discovered, that the communication with Slurm was not possible due to the container isolation and a container is not desired for our use. We also discovered, that an outdated Slurm-Web version was installed with an outdated Pyslurm, which is incompatible with the current Slurm version. Therefore, we decided to create a bash script to install and build the newest version on the server with the newest dependencies. 
Dependencies: 
        ◦ Pyslurm v19.05.0 (https://github.com/PySlurm/pyslurm/tree/19.05.0)
        ◦ Slurm-Web v2.2.6 (https://github.com/edf-hpc/slurm-web/releases/tag/debian%2F2.2.6)
        ◦ the obsolete Python 2 was replaced by Python 3 with 2to3 (https://packages.ubuntu.com/bionic/2to3) 
Even though we adjusted the dependencies to Python 3 and fixed the major errors we encountered, several other (already known) problems (for example (https://github.com/edf-hpc/slurm-web/issues/213, https://github.com/edf-hpc/slurm-web/issues/183 ...)

# Result
A simply convertation from Python 2 to Python 3 with, further d 2to3 is not possible. It is necessary to debugging all dependencies manually.  
Dependencies are using out of date modules, which causes AttributErrors. Those have to be fixed manually for each file. However, the changes cause new error messages because the functions are slightly different from the original function. 
Slurm web is apparently not well maintained and there is no more active development and issue fixing. We are running into errors from issues that have been open for years.

Our conclusion is therefore that Slurm-Web is unfortunately not usable for future projects.

**Comment by jkrue** [comment]
Thx for your brief summary.
