### ISSUE TITLE
configuration files error

### ISSUE THREAD

**Issue by ChiaraVanni** [BiBiServ/bibigrid#411]
Hi,
I am trying to build a cluster using BiBigrid but I am getting the following error when checking the configuration:

```
./bibigrid.sh -i bibigrid.yml -ch -vv
2023-05-24 18:52:49,095 [DEBUG] Logging verbosity set to 2
2023-05-24 18:52:49,097 [DEBUG] File clouds.yaml found in folder ~/.config/bibigrid.
2023-05-24 18:52:49,098 [DEBUG] File clouds-public.yaml in folder ~/.config/bibigrid not found.
2023-05-24 18:52:49,098 [DEBUG] File clouds-public.yaml in folder /etc/bibigrid not found.
2023-05-24 18:52:49,098 [DEBUG] File clouds-public.yaml in folder  not found.
**2023-05-24 18:52:49,098 [ERROR] 'str' object has no attribute 'get'**
--- 0 minutes and 0.001583099365234375 seconds ---
```
I get the same error both using a clouds.yaml file with username and password and one with the application credentials.
Here's the link to the files I'm using (I removed the sensible/personal data):
https://drive.google.com/drive/folders/1Cvxglbd-Aot8HHXQCpw_K5ZgozwBYuCB?usp=share_link

I am probably missing something obvious, but any suggestion on where the error could be would be appreciated!

Thank you!

Chiara

**Comment by XaverStiensmeier** [comment]
Hey,
thank you very much for opening this issue. The underlying problem isn't very obvious, because it is in the `bibigrid.yml` file and the error message is quite cryptic.

BiBiGrid expects a list of configurations. This is due to the fact that the "new" BiBiGrid was designed with multi-cloud in mind. We are currently working on releasing those features, but the configuration being a list is a symptom of this thinking.

Because you only have one configuration (one cloud location) you need to make the entire current content the first (and only) list element by adding `-` and indenting the rest accordingly.

This would be the "corrected" file:
[bibigrid.txt](https://github.com/BiBiServ/bibigrid/files/11558539/bibigrid.txt)

---
I've immediately implemented a solution for this issue. In the future using a single configuration without a list will not crash anymore, but print a warning and run as expected. However, since we are currently getting the big multi-cloud feature ready, it will take some time before this nicer error handling will be available.

**Comment by ChiaraVanni** [comment]
Hi! 
Thank you for the quick answer! Writing it as a list solved the problem.
