### ISSUE TITLE
Password not set... 

### ISSUE THREAD

**Issue by karl616** [BiBiServ/bibigrid#94]
Hi, 

this might be a naive question, but I would appreciate help all the same.

I'm trying to get bibigrid running on the HD-HuB instance of the de.NBI cloud. I had something running when I had a local account there, but after the transition to elixir accounts I have a problem. I must be missing something, but my only method of authentication is through the key-pair I provided on the elixir site.

Bibigrid require password based authentication, or at least the config file does not validate if I leave the password field empty. Is there an easy solution to this?

Best,
Karl

**Comment by jkrue** [comment]
Dear Karl,

please contact the cloud administrators of HD-Hub ( denbi-cloud@bioquant.uni-heidelberg.de) to setup a password
for your (exlixir) account.

For application which uses the Openstack API (like the Openstack CLI tools or the BiBiGrid) a  user/password needed
since web direction is not possible.


Regards,

Jan


> On 25. Jan 2019, at 09:55, Karl Nordström <notifications@github.com> wrote:
> 
> Hi,
> 
> this might be a naive question, but I would appreciate help all the same.
> 
> I'm trying to get bibigrid running on the HD-HuB instance of the de.NBI cloud. I had something running when I had a local account there, but after the transition to elixir accounts I have a problem. I must be missing something, but my only method of authentication is through the key-pair I provided on the elixir site.
> 
> Bibigrid require password based authentication, or at least the config file does not validate if I leave the password field empty. Is there an easy solution to this?
> 
> Best,
> Karl
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Jan Krüger

Bielefeld University Bioinformatics Server (BiBiServ)
Center for Biotechnology (CeBiTec)

Bielefeld University
Faculty of Technology
33594 Bielefeld,Germany

room    : M3-120
phone  : +49 (521) 106 2494

**Comment by karl616** [comment]
Thanks for the fast response!

I will do that.
